create table if not exists public.vehicles (
    id bigint generated by default as identity primary key,
    ngay text not null,
    ngay_nhan_xe text,
    bien_so text not null,
    loai_xe text not null,
    tinh_trang text not null,
    vi_tri text not null,
    so_km_hien_tai bigint not null default 0,
    ngay_bao_duong_gan_nhat text,
    so_km_bao_duong_gan_nhat bigint not null default 0,
    so_km_bao_duong_du_kien bigint not null default 0,
    created_at timestamptz not null default now()
);

alter table public.vehicles
    add column if not exists ngay_nhan_xe text,
    add column if not exists so_km_hien_tai bigint not null default 0,
    add column if not exists ngay_bao_duong_gan_nhat text,
    add column if not exists so_km_bao_duong_gan_nhat bigint not null default 0,
    add column if not exists so_km_bao_duong_du_kien bigint not null default 0;

alter table public.vehicles enable row level security;

drop policy if exists "vehicles_public_read" on public.vehicles;
create policy "vehicles_public_read"
on public.vehicles for select
to anon, authenticated
using (true);

drop policy if exists "vehicles_public_insert" on public.vehicles;
create policy "vehicles_public_insert"
on public.vehicles for insert
to anon, authenticated
with check (true);

drop policy if exists "vehicles_public_update" on public.vehicles;
create policy "vehicles_public_update"
on public.vehicles for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "vehicles_public_delete" on public.vehicles;
create policy "vehicles_public_delete"
on public.vehicles for delete
to anon, authenticated
using (true);

-- Chạy phần này nếu bảng shift_reports đang bật RLS.
alter table public.shift_reports enable row level security;

drop policy if exists "shift_reports_public_read" on public.shift_reports;
create policy "shift_reports_public_read"
on public.shift_reports for select
to public
using (true);

drop policy if exists "shift_reports_public_insert" on public.shift_reports;
create policy "shift_reports_public_insert"
on public.shift_reports for insert
to public
with check (true);

drop policy if exists "shift_reports_public_update" on public.shift_reports;
create policy "shift_reports_public_update"
on public.shift_reports for update
to public
using (true)
with check (true);

drop policy if exists "shift_reports_public_delete" on public.shift_reports;
create policy "shift_reports_public_delete"
on public.shift_reports for delete
to public
using (true);
